remove .terraform.lock.hcl file
Attempting to fix error:

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
locked provider registry.terraform.io/hashicorp/aws 5.43.0 does not match
configured version constraint >= 4.0.0, >= 4.66.1, >= 5.37.0, >= 5.46.0; must
use terraform init -upgrade to allow selection of new versions